name: fitapp
version: "3.9"

services:
  frontend:
    build: ./frontend
    image: fitapp-frontend:dev
    pull_policy: missing
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    image: fitapp-backend:dev
    pull_policy: missing
    ports:
      - "8080:8080"